//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentDetail
    {
        public int PaymentDetailID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public string Description { get; set; }
    }
}
