//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public bool IsBank { get; set; }
        public bool Active { get; set; }
    }
}
